name: Build and Release uYouPlus

on:
  workflow_dispatch:
    inputs:
      uyou_version:
        description: "The version of uYou"
        default: "3.0.4"
        required: true
        type: string
      uyou_url:
        description: "The URL to download uYou"
        default: "https://something.url/uyou.deb"
        required: false
        type: string
      decrypted_youtube_url:
        description: "Direct URL to decrypted YouTube IPA. YouTube version is detected automatically."
        default: ""
        required: true
        type: string
      bundle_id:
        description: "Custom Bundle ID (Not recommended)"
        default: "com.google.ios.youtube"
        required: true
        type: string
      app_name:
        description: "Custom app name for Home Screen (Not recommended)"
        default: "YouTube"
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean
      upload_artifact:
        description: "Upload built artifact"
        default: false
        required: false
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build uYouPlus
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main
          submodules: recursive

      - name: Cache and Install Homebrew Dependencies
        id: brew_cache
        uses: tecolicom/actions-use-homebrew-tools@v1.2
        with:
          tools: ldid dpkg make
          cache: true

      - name: Install Dependencies if Needed
        if: steps.brew_cache.outputs.cache-hit != 'true'
        run: brew install ldid dpkg make

      - name: Add make to PATH
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Checkout Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Cache iOS 16.5 SDK
        id: sdk_cache
        uses: actions/cache@v4
        with:
          path: theos/sdks
          key: ios-sdk-16.5

      - name: Download iOS 16.5 SDK
        if: steps.sdk_cache.outputs.cache-hit != 'true'
        run: |
          git clone -n --depth=1 --filter=tree:0 https://github.com/theos/sdks.git tmp_sdks
          cd tmp_sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Checkout Theos Jailed
        uses: actions/checkout@v4
        with:
          repository: qnblackcat/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare YouTube IPA
        id: prepare_youtube
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
          cd main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "YouTube version: $youtube_version"
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
        env:
          THEOS: ${{ github.workspace }}/theos
          YOUTUBE_URL: ${{ inputs.decrypted_youtube_url }}

      - name: Patch Makefile and Build Package
        id: build_package
        run: |
          mkdir -p theos/lib/iphone/rootless
          cd main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
          ipa_file=$(ls -t packages/*.ipa | head -n1)
          echo "package=$(basename $ipa_file)" >> $GITHUB_OUTPUT
          echo "SHA256: $(shasum -a 256 $ipa_file | cut -d' ' -f1)"
        env:
          THEOS: ${{ github.workspace }}/theos
          UYOU_VERSION: ${{ inputs.uyou_version }}
          UYOU_URL: ${{ inputs.uyou_url }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          APP_NAME: ${{ inputs.app_name }}

      - name: Upload Built Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: uYouPlus_${{ steps.prepare_youtube.outputs.youtube_version }}_${{ inputs.uyou_version }}
          path: main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create GitHub Release
        if: ${{ inputs.create_release }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.prepare_youtube.outputs.youtube_version }}-${{ inputs.uyou_version }}-${{ github.run_number }}
          name: v${{ steps.prepare_youtube.outputs.youtube_version }}-${{ inputs.uyou_version }}-${{ github.run_number }}
          draft: true
          files: main/packages/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
